openrouter:
  base_url: "https://openrouter.ai/api/v1"

test:
  temperature: 0
  max_tokens: 1024
  repeats: 1  # Set to 3 for official testing to evaluate response stability across runs
  default_system_prompt: "You are a helpful assistant." #Put default system prompt here when we have one
